language: android
dist: trusty
install:
  - cp travis_licenses/licenses.xml TeamCode/src/main/res/values/licenses.xml
android:
  components:
    - build-tools-28.0.3
    - android-28
    - extra-google-m2repository
    - extra-android-m2repository
